#!/bin/sh
process() {
  if [ -s $1 ]
  then
    if [ "$3" = "-v" ]
    then
      echo "Processing $1"
    fi
    if ~/bin/isspam -$2 $1 $3
    then
      > $1
    fi
  fi
}

verbose=`getopt v $*`
process ~/Mail/Deleted/spam y $verbose
process ~/Mail/Deleted/good n $verbose
