#!/bin/sh
process() {
  if [ -s $1 ]
  then
    if [ "$3" = "-v" ]
    then
      echo "Processing $1"
    fi
    ~/bin/isspam -$2 $1 $3
    > $1
  fi
}

verbose=`getopt v $*`
process ~/Mail/Deleted/spam y $verbose
process ~/Mail/Deleted/good n $verbose
